# Generated by Django 5.2.14 on 2026-06-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("password", models.CharField(max_length=128)),
                ("nickname", models.CharField(blank=True, default="", max_length=64)),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(0, "普通用户"), (1, "管理员")], default=0
                    ),
                ),
                ("register_time", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
        ),
    ]
