# Generated by Django 5.2.14 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "cat_id",
                    models.AutoField(
                        db_column="cat_id", primary_key=True, serialize=False
                    ),
                ),
                ("cat_name", models.CharField(max_length=64)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书类目",
                "verbose_name_plural": "图书类目",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="BookBase",
            fields=[
                (
                    "book_id",
                    models.AutoField(
                        db_column="book_id", primary_key=True, serialize=False
                    ),
                ),
                ("isbn", models.CharField(db_index=True, max_length=20, unique=True)),
                ("book_name", models.CharField(db_index=True, max_length=200)),
                ("author", models.CharField(blank=True, default="", max_length=128)),
                ("publisher", models.CharField(blank=True, default="", max_length=128)),
                ("pub_year", models.IntegerField(blank=True, null=True)),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("book_desc", models.TextField(blank=True, default="")),
                (
                    "tags",
                    models.CharField(
                        blank=True, default="", help_text="逗号分隔标签", max_length=256
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="cat_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书基础信息",
                "verbose_name_plural": "图书基础信息",
                "db_table": "book_base",
                "indexes": [
                    models.Index(
                        fields=["category"], name="book_base_cat_id_70fe30_idx"
                    )
                ],
            },
        ),
    ]
