# Generated by Django 5.2.14 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(unique=True)),
                ("new_users", models.IntegerField(default=0)),
                ("new_sells", models.IntegerField(default=0)),
                ("orders_done", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                ("report_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_report",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorLog",
            fields=[
                (
                    "log_id",
                    models.AutoField(
                        db_column="log_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "浏览"),
                            (2, "咨询"),
                            (3, "点击"),
                            (4, "收藏"),
                            (5, "下单"),
                        ]
                    ),
                ),
                ("stay_time", models.IntegerField(default=0, help_text="停留秒数")),
                ("action_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sell",
                    models.ForeignKey(
                        db_column="sell_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_logs",
                        to="marketplace.sellbook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behavior_logs",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "行为日志",
                "verbose_name_plural": "行为日志",
                "db_table": "behavior_log",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="behavior_lo_user_id_019800_idx"
                    ),
                    models.Index(
                        fields=["sell_id"], name="behavior_lo_sell_id_d61e0b_idx"
                    ),
                    models.Index(
                        fields=["action_time"], name="behavior_lo_action__2f5cfc_idx"
                    ),
                ],
            },
        ),
    ]
