# Generated by Django 5.2.14 on 2026-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="running", max_length=16)),
                ("message", models.TextField(blank=True, default="")),
                ("records_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "crawler_log",
                "ordering": ["-started_at"],
            },
        ),
    ]
