# Generated by Django 5.2.14 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellBook",
            fields=[
                (
                    "sell_id",
                    models.AutoField(
                        db_column="sell_id", primary_key=True, serialize=False
                    ),
                ),
                ("second_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quality", models.SmallIntegerField(default=3, help_text="成色1-5级")),
                ("cover_img", models.CharField(blank=True, default="", max_length=512)),
                ("view_count", models.IntegerField(default=0)),
                ("collect_count", models.IntegerField(default=0)),
                ("consult_count", models.IntegerField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "下架"), (1, "在售")], db_index=True, default=1
                    ),
                ),
                (
                    "is_hot",
                    models.BooleanField(default=False, help_text="热度模型标记"),
                ),
                (
                    "is_anomaly",
                    models.BooleanField(default=False, help_text="异常高价/滞销标记"),
                ),
                (
                    "audit_status",
                    models.SmallIntegerField(default=1, help_text="0待审1通过2拒绝"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_items",
                        to="catalog.bookbase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_books",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "在售图书",
                "verbose_name_plural": "在售图书",
                "db_table": "sell_book",
            },
        ),
        migrations.CreateModel(
            name="Collect",
            fields=[
                (
                    "collect_id",
                    models.AutoField(
                        db_column="collect_id", primary_key=True, serialize=False
                    ),
                ),
                ("collect_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collects",
                        to="accounts.user",
                    ),
                ),
                (
                    "sell",
                    models.ForeignKey(
                        db_column="sell_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collects",
                        to="marketplace.sellbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "db_table": "collect",
            },
        ),
        migrations.AddIndex(
            model_name="sellbook",
            index=models.Index(fields=["book_id"], name="sell_book_book_id_eabcef_idx"),
        ),
        migrations.AddIndex(
            model_name="sellbook",
            index=models.Index(fields=["user_id"], name="sell_book_user_id_0b157c_idx"),
        ),
        migrations.AddIndex(
            model_name="sellbook",
            index=models.Index(fields=["status"], name="sell_book_status_5e3c4d_idx"),
        ),
        migrations.AddIndex(
            model_name="collect",
            index=models.Index(
                fields=["user_id", "sell_id"], name="collect_user_id_24513d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collect",
            unique_together={("user", "sell")},
        ),
    ]
