# Generated by Django 5.2.14 on 2026-06-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("msg_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="accounts.user",
                    ),
                ),
                (
                    "sell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="marketplace.sellbook",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "message",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "order_id",
                    models.CharField(
                        default="", max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("deal_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待沟通"),
                            (1, "沟通中"),
                            (2, "待交易"),
                            (3, "已完成"),
                        ],
                        default=0,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        db_column="buyer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_orders",
                        to="accounts.user",
                    ),
                ),
                (
                    "sell",
                    models.ForeignKey(
                        db_column="sell_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="marketplace.sellbook",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        db_column="seller_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_orders",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order_info",
                "indexes": [
                    models.Index(
                        fields=["buyer_id"], name="order_info_buyer_i_7f8535_idx"
                    ),
                    models.Index(
                        fields=["seller_id"], name="order_info_seller__bcbd19_idx"
                    ),
                    models.Index(
                        fields=["sell_id"], name="order_info_sell_id_cf08bf_idx"
                    ),
                ],
            },
        ),
    ]
